## Default values for tmf635-usage.###################
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

replicaCount: 1

env:
  name: password
  value: "MyValue"
image:
  repository: REPO_URL
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: false
  ingressClassName: traefik
  annotations: {}
  path: /
  hosts:
    - test.akhilsathyan.tech
  tls:
    - secretName: new-tls
      hosts:
        - test.akhilsathyan.tech

hpa:
  enabled: true
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}
